# Generated by Django 3.2.9 on 2021-12-14 11:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên khóa học')),
                ('ctype', models.CharField(max_length=50, verbose_name='Loại khóa học')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Ngày bắt đầu')),
                ('status', models.CharField(choices=[('opening', 'Đang mở để đăng ký'), ('inprogress', 'Đang tiến hành'), ('ended', 'Đã kết thúc')], max_length=50, verbose_name='Trạng thái khóa học')),
                ('tuition_fee', models.FloatField(verbose_name='Học phí')),
                ('description', models.TextField(verbose_name='Mô tả khóa học')),
                ('schedule', models.TextField(verbose_name='Lịch trình')),
                ('cover_image', models.ImageField(upload_to='', verbose_name='Ảnh minh họa')),
                ('cover_image_binary', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('assignment', 'Bài tập'), ('document', 'Tài liệu')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('star', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Điểm')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Khóa học')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CourseTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, verbose_name='Vai trò')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Ngày tham gia khóa học')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Khóa học')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Giảng viên')),
            ],
            options={
                'unique_together': {('teacher', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CourseStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Ngày tham gia khóa học')),
                ('score', models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Điểm tổng kết')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Khóa học')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Học viên')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
