# Generated by Django 3.2.9 on 2021-12-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_coursestudents_courseteachers_material_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Ảnh minh họa'),
        ),
    ]
