# Generated by Django 3.2.9 on 2021-12-27 10:56

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('opening', 'Đang mở để đăng ký'), ('inprogress', 'Đang tiến hành'), ('ended', 'Đã kết thúc')], default='opening', max_length=50, verbose_name='Trạng thái khóa học'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Số sao'),
        ),
    ]
